runtime: python # or another supported version
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /result
  static_dir: static/detections

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto