runtime: python39 # or another supported version

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /result
  static_dir: static/detections

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto